service: sls-rust-example

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  hello_world:
    handler: handler.hello_world
    events:
      - http:
          path: hello-world
          method: get
          cors: true

plugins:
  - serverless-rust
