[package]
name = "todos_dynamodb"
version = "0.1.0"
authors = ["MIYASHITA, Akihiro <miya@gameplus.info>"]

[dependencies]
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rusoto_core = "*"
rusoto_dynamodb = "*"
